timeout: 40m
steps:
  - name: 'docker.io/hashicorp/terraform:0.12.18'
    args: ['init']

  - name: 'docker.io/hashicorp/terraform:0.12.18'
    args: ['workspace', 'select', '${BRANCH_NAME}']

  - name: 'docker.io/hashicorp/terraform:0.12.18'
    args: ['apply', '-auto-approve']
    timeout: 30m
